function filedata = import_file_data(filename, dataLines)
%IMPORTFILE Import data from a text file
%  NORMALDATAMAR2614TIME15221 = IMPORTFILE(FILENAME) reads data from
%  text file FILENAME for the default selection.  Returns the data as a
%  table.
%
%  NORMALDATAMAR2614TIME15221 = IMPORTFILE(FILE, DATALINES) reads data
%  for the specified row interval(s) of text file FILENAME. Specify
%  DATALINES as a positive scalar integer or a N-by-2 array of positive
%  scalar integers for dis-contiguous row intervals.
%
%  Example:
%  NormalDataMar2614Time15221 = importfile("/Users/user/Documents/UMD2023/ENME485/Assignments/HW2/Reading Materials/Training/Healthy/Normal Data Mar-26-14 Time 1522-1.txt", [6, Inf]);
%
%  See also READTABLE.
%
% Auto-generated by MATLAB on 20-Sep-2023 14:03:45

%% Input handling

% If dataLines is not specified, define defaults
if nargin < 2
    dataLines = [6, Inf];
end

%% Set up the Import Options and import the data
opts = delimitedTextImportOptions("NumVariables", 1);

% Specify range and delimiter
opts.DataLines = dataLines;
opts.Delimiter = ",";

% Specify column names and types
% opts.VariableNames = "Date3262014";
opts.VariableTypes = "double";

% Specify file level properties
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";

% Import the data
filedata = readtable(filename, opts);
filedata = table2array(filedata);

end